### ISSUE TITLE
Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by ajimix** [revolist/vue3-datagrid#4] opened 2021-06-26 18:37 UTC
As reported here: https://github.com/revolist/vue-datagrid/issues/19

I'm encountering the same problem when testing in Chrome latest and Safari latest, with the basic code from the example and using Webpack:

```
Uncaught Error: Automatic publicPath is not supported in this browser
    at eval (vgrid.js?675a:1)
    at eval (vgrid.js?675a:1)
    at eval (vgrid.js?675a:1)
    at eval (vgrid.js?675a:1)
    at eval (vgrid.js?675a:1)
    at Object../node_modules/@revolist/vue3-datagrid/dist/vgrid.js
```

```vue
<template>
  <div id="app">
    <v-grid theme="compact" :source="rows" :columns="columns"/>
  </div>
</template>

<script>
import VGrid from "@revolist/vue3-datagrid";
export default {
  name: "App",
  data() {
    return {
      columns: [{
          prop: "name",
          name: "First",
        },
        {
          prop: "details",
          name: "Second",
      }],
      rows: [{
        name: "1",
        details: "Item 1",
      }]
    };
  },
  components: {
    VGrid,
  },
};
</script>
```

**Comment by namcusamlc** [comment] 2021-07-23 07:10
I face the same problem too
I was working with Laravel Nova and writing a Tool for it.
I tried to use this package but it always show this Automatic publicPath error.

**Comment by sergeich5** [comment] 2021-07-28 18:06
> I face the same problem too
> I was working with Laravel Nova and writing a Tool for it.
> I tried to use this package but it always show this Automatic publicPath error.

+1, the same problem right now. Idk how to solve that

**Comment by Super-Chama** [comment] 2021-09-22 12:06
Have the same issue when using `vue-test-utils` to run unit tests. tried declaring `publicPath` in `vue.config.js` without any change. Looks like issue with vue async component declared in the vue adaptor, maybe consider using regular vue component ?

**Comment by alfikr** [comment] 2021-10-30 07:42
> I face the same problem too I was working with Laravel Nova and writing a Tool for it. I tried to use this package but it always show this Automatic publicPath error.

+1 same here

**Comment by avatarbabe** [comment] 2022-01-23 09:29
Same issue here with Vite + Vue 3 but only when building for production.

**Comment by lijie1129** [comment] 2022-02-09 23:53
#18

**Comment by pavel-barton** [comment] 2022-03-03 17:43
I am currently using vue 3 + vite and I can confirm that the fix provided by @lijie1129 resolves the issue.

**Comment by revolist** [comment] 2022-08-13 13:01
Merged, added better vite support. Was planning to use it in 4.0+ but wasn't delivered yet.

**Closed by revolist** 2022-08-13 13:01 UTC
